# Generated by Django 4.2.2 on 2023-07-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appunidad7', '0005_remove_pedidoproducto_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.CharField(default='url', max_length=250),
        ),
    ]
