# Generated by Django 4.2.2 on 2023-07-19 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appunidad7', '0007_alter_pedido_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidoproducto',
            old_name='subtotal',
            new_name='precio_unitario',
        ),
        migrations.RemoveField(
            model_name='pedidoproducto',
            name='productos',
        ),
        migrations.AddField(
            model_name='pedidoproducto',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pedidoproducto',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appunidad7.producto'),
        ),
        migrations.AlterField(
            model_name='pedidoproducto',
            name='pedido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appunidad7.pedido'),
        ),
    ]
